server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: iorecycling-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: iorecycling-backend
          service: iorecycling-backend
          __path__: /opt/iorecycling/logs/backend/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            tenantId: tenantId
            userId: userId
            traceId: traceId
            http_status_code: http_status_code
            http_route: http_route
            exception_type: exception_type
      - labels:
          level:
          tenantId:
          exception_type:
          http_status_code:
